import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/footer";
import { ClerkProvider } from "@clerk/nextjs";

// ✅ Make sure this is above RootLayout
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // optional but good to include
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${roboto.className} flex min-h-screen flex-col`}
          suppressHydrationWarning
        >
          <Header />
          <main className="flex-1 overflow-auto">{children}</main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
